---
swagger: "2.0"
info:
  description: "Create incidents when machines are broken\n"
  version: "1.0"
  title: "MachineIncident"
host: "sagdemo.gateway.webmethodscloud.com"
basePath: "/gateway/MachineIncident/1.0"
schemes:
- "http"
security:
- apiKey: []
paths:
  /incident:
    post:
      operationId: "fl38b55caf88995d476c5cb6"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/body"
      responses:
        200:
          description: "OK"
        401:
          description: "Access Denied"
securityDefinitions:
  apiKey:
    type: "apiKey"
    name: "x-Gateway-APIKey"
    in: "header"
definitions:
  body:
    type: "object"
    required:
    - "component"
    - "componentStatusDescription"
    - "machineId"
    - "status"
    properties:
      component:
        type: "string"
      machineId:
        type: "string"
      componentStatusDescription:
        type: "string"
      status:
        type: "string"
